#!/bin/bash

set -euxoH pipefail

WEBSITES=$(kubectl get websites.kubecon.bmutziu.me --output json | jq '.items | length')
[[ ${WEBSITES} -eq 0 ]] || echo "You should have deleted the website installed in the cluster. Currently you have ${WEBSITES} installed."  

DEPLOYMENTS=$(kubectl get deployment -ltype=Website --output json| jq '.items | length')
[[ ${DEPLOYMENTS} -eq 0 ]] || echo "Your delete should have deleted the deployment. Currently you have ${DEPLOYMENTS} deployments."

SERVICES=$(kubectl get services -ltype=Website --output json| jq '.items | length')
[[ ${SERVICES} -eq 0 ]] || echo "Your delete should have deleted the service. Currently you have ${SERVICES} service."
