#!/bin/bash

source ~/.bashrc > /dev/null 2>&1

echo '
apiVersion: kubecon.bmutziu.me/v1beta1
kind: Website
metadata:
  name: website-sample
spec:
  imageTag: latest
' > ${DEMO_HOME:?}/config/samples/kubecon_v1beta1_website-with-image-tag.yaml
