#!/bin/bash

set -euxoH pipefail
source ~/.bashrc > /dev/null 2>&1

[[ -f ${DEMO_HOME:?}/api/v1beta1/website_types.go ]] || echo "The CRD called Website has not been generated, did create a resource when running the 'create api' command?"  
[[ -f ${DEMO_HOME:?}/internal/controller/website_controller.go ]] || echo "The controller called website has not been generated, did you create a controller when running the 'create api' command?" 
