#!/bin/bash

set -euxoH pipefail

grep "errors.IsAlreadyExists(err)" ${DEMO_HOME:?}/internal/controller/website_controller.go || echo "Have you successfully handled an 'already exists' error message?"
