#!/bin/bash

set -euxoH pipefail
source ~/.bashrc > /dev/null 2>&1

GO_MOD=${DEMO_HOME:?}/go.mod
[[ -f ${GO_MOD} ]] || echo "You do not seem to have a created an application. Did you run the kubebuilder init command?"

EXPECTED_GOMOD="""module github.com/bmutziu/instruqt-kubecon

go 1.19"""

ACTUAL_GOMOD=$(head -n3 ${GO_MOD})
[[ ${EXPECTED_GOMOD} = ${ACTUAL_GOMOD} ]] || echo "go.mod is unexpected, did you run kubebuilder init?"  
