#!/bin/bash

set -euxoH pipefail
source ~/.bashrc > /dev/null 2>&1

WEBSITES=$(kubectl get websites.kubecon.bmutziu.me --output json | jq '.items | length')
[[ ${WEBSITES} -eq 1 ]] || echo "You should have 1 website installed in the cluster. Currently you have ${WEBSITES} installed."  
