#!/bin/bash

set -euxoH pipefail
source ~/.bashrc > /dev/null 2>&1

cd /root
rm -rf ${DEMO_HOME:?}
cp -R ${SOLUTIONS_DIR:?}/05-introduce-and-view-controller-specific-logs ${DEMO_HOME:?}

cd ${DEMO_HOME:?}
make install
kubectl delete websites.kubecon.bmutziu.me website-sample || true
kubectl wait --for condition=established --timeout=60s crd/websites.kubecon.bmutziu.me
kubectl apply --filename config/samples/kubecon_v1beta1_website.yaml
