#!/bin/bash

set -euxoH pipefail
source ~/.bashrc > /dev/null 2>&1

echo ${DEMO_HOME:?}
echo ${SOLUTIONS_DIR:?}

cd /Users/bmutziu
rm -rf ${DEMO_HOME:?}
cp -R ${SOLUTIONS_DIR:?}/01-get-to-know-the-platform ${DEMO_HOME:?}

cd ${DEMO_HOME:?}
kubectl apply --filename .example-namespace.yaml
